export default function Disclaimer({ className = '' }) {
  return (
    <div className={`bg-amber-50 border border-amber-200 rounded-lg p-4 text-sm text-amber-800 ${className}`}>
      <p className="font-semibold mb-1">Important Notice</p>
      <p>
        This tool provides informational and organizational assistance only. It does <strong>not</strong> constitute
        legal advice and does not create an attorney-client relationship. Results are generated by AI and may contain
        errors or omissions. Always consult a licensed immigration attorney before making any legal decisions.
      </p>
    </div>
  )
}
